### ISSUE TITLE
Degree Symbol Error

### ISSUE THREAD

**Issue by IIAIronWolf** [protostax/ProtoStax_Weather_Station_Demo#1]
When I run this code, the program is writing, for example, **50\&#xb0F** instead of **50°F.** I cannot figure out how to get this to work properly. I have tried changing the unicode for degree (°) but I am getting errors like, " _UnicodeEncodeError: 'ascii' codec can't encode character u'\..._ "

**Comment by IIAIronWolf** [comment]
Finally got a fix by replacing each of the lines that say **u'\&#xb0'** with **char(176)**

**Comment by sridharrajagopal** [comment]
What character set are you using in your environment?

**Comment by IIAIronWolf** [comment]
I left your code untouched, which seems to use UTF-8.

**Comment by sridharrajagopal** [comment]
Ok, thanks for the clarification. I actually meant your own RPi environment. I'm trying to understand what might be different. Btw, you said 

"Finally got a fix by replacing each of the lines that say u'&#xb0' with char(176)" 

But I don't have u'&#xb0' but rather u'\u00b0' in code (they are the same thing of course), so wanted to clarify. 

Thanks,
Sridhar

**Comment by IIAIronWolf** [comment]
Sorry, I’m still learning the lingo haha. 
But yes I changed it to &#xb0 because when I used u’\u00b0’ I was getting the “UnicodeEncodeError: 'ascii' codec can't encode character...” message.  I’m not sure what could be different on my rPi though. I just got it and started from scratch with this project.

**Comment by IIAIronWolf** [comment]
From my google searching I was finding this could be caused by trying to Unicode encode a string value, and that the .encode command should be used (but I don’t know enough about it to make any suggestions).

**Comment by sridharrajagopal** [comment]
Hi there, 

Yes, thanks for the research and suggestion! I will look into it and update as necessary. I also need to figure out what changed, or what is different, because the project worked fine as-is!

Thanks again, 
Sridhar

**Comment by sridharrajagopal** [comment]
Ok, I finally had some time to try it out on a clean slate environment (using Raspbian Buster). I noticed the problem using python 2.7.16. 

When using python 3.7 (python 3.7.3 to be precise), my code as-is worked fine. (The code assumes python 3 btw, with the epaper library and code in general) You do have to install pyowm using pip3 to use it with python 3 installation though. 

I will update the README to reflect that. Thanks for pointing this out! 

Hope that helps! 
Cheers,
Sridhar

**Comment by sridharrajagopal** [comment]
Btw, with python 2.7, you'd have to replace 

tempstr = str("{0}{1}F".format(int(round(temperature['temp'])), u'\u00b0'))

with 

tempstr = str("{0}{1}F".format(int(round(temperature['temp'])), u'\u00b0'.encode('utf-8'))

Basically, in python 3 and above, all literals are in unicode, so it doesn't a problem with my original code. 

In python 2, the first string literal is in ascii, whereas the 2nd argument string is in unicode, and hence python complains. 

But as I mentioned, the library assumes python3, so the best solution is to just run it with python 3! 

Hope that helps as well! 
Cheers, 
Sridhar
